### ISSUE TITLE
More description

### ISSUE THREAD

**Issue by rlczddl** [diegothomas/SegmentedFusion#1]
Hi, I am very interested in this project, can you add more description, such as algorithm flow, algorithm results, etc？

**Comment by diegothomas** [comment]
Hi. Thank you very much for your interest in our work.

Here is the paper that corresponds to this code
Yao, Shih Hsuan, et al. "SegmentedFusion: 3D human body reconstruction using stitched bounding boxes." 2018 International Conference on 3D Vision (3DV). IEEE, 2018

https://ieeexplore.ieee.org/abstract/document/8490969

**Comment by rlczddl** [comment]
Thanks for the update!
